name: Continuous Deployment

on: workflow_dispatch

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v6

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v5

      - name: 💚 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔎 Typecheck code
        run: pnpm typecheck

      - name: 🔎 Lint code
        run: pnpm lint

      - name: 🚀 Build code and deploy app
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOOLS_TOKEN: ${{ secrets.HOMEBREW_TOOLS_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
